// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSource = "steam" | "xbox" | "epic" | "gog" | "ea" | "startmenu" | "manual";
