// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonState } from "./ButtonState";

export type ControllerEvent = { button: number, state: ButtonState, timestamp: number, duration: number, };
