// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { MacroMode } from "./MacroMode";

export type MacroAction = { action: ActionKind, mode: MacroMode, 
/**
 * e.g. "button:0", "combo:4+5"
 */
trigger: string, 
/**
 * app id, key sequence, page name, script path.
 */
target: string, chain: Array<MacroAction>, };
