// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderState } from "./ProviderState";

export type ProviderReport = { provider: string, state: ProviderState, count: number, error: string | null, elapsed_ms: number, };
