// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for the `library_running` command + the
 * `library:running:changed` event payload.
 */
export type RunningGame = { id: string, name: string, pid: number, started_at: number, attached: boolean, };
