// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEntry } from "./AppEntry";
import type { ProviderReport } from "./ProviderReport";

export type ScanResult = { entries: Array<AppEntry>, providers: Array<ProviderReport>, };
