// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptionEvent = { text: string, is_final: boolean, timestamp: number, };
