// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One audio input device, as returned by `voice_get_devices`.
 */
export type VoiceDevice = { id: string, name: string, is_default: boolean, };
