// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionKind = "voice_record" | "launch_app" | "send_keys" | "navigate_ui" | "run_script" | "chain";
