// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSource } from "./AppSource";

export type AppEntry = { id: string, name: string, source: AppSource, launch_command: string, exe_path: string | null, icon_path: string | null, art_url: string | null, metadata: Record<string, unknown>, };
