// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `controller_get_state`. Pane 8 owns the gilrs-backed implementation
 * and may extend the shape; this is the minimum surface the IPC boundary
 * promises today (matches the stub fixture).
 */
export type ControllerState = { connected: boolean, buttons: Array<number>, axes: Array<number>, };
