// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `playtime_get` — total tracked minutes + epoch-seconds of last
 * session. Matches the keys Pane 5's stub returns and the helpers on
 * [`AppEntry`].
 */
export type Playtime = { minutes: number, last_played: number, };
