// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawgGameData = { id: number, name: string, description: string, rating: number, metacritic: number, genres: Array<string>, platforms: Array<string>, screenshots: Array<string>, playtime: number, background_image: string, released: string, };
