// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TwitchStream = { user_name: string, title: string, viewer_count: number, thumbnail_url: string, stream_url: string, };
