// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single YouTube video search result (mapped from `services/youtube.py::YouTubeResult`).
 */
export type YouTubeTrailer = { video_id: string, title: string, thumbnail_url: string, channel: string, };
